/*
 * DialogoTransformadaFourier.java
 *
 * Created on 2 de mayo de 2008, 11:58
 */

package es.upm.fi.gtd.first.dialogos;

import es.upm.fi.gtd.first.Accesorio;
import es.upm.fi.gtd.first.Atrous;
import es.upm.fi.gtd.first.CargaAux;
import es.upm.fi.gtd.first.Dialogos;
import es.upm.fi.gtd.first.DialogosAux;
import es.upm.fi.gtd.first.ExampleFileFilter;
import es.upm.fi.gtd.first.GeoImg;
import es.upm.fi.gtd.ij.FFTMod;
import ij.ImagePlus;
import java.awt.Image;
import java.awt.image.DataBuffer;
import java.awt.image.RenderedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.media.jai.PlanarImage;
import javax.swing.JFileChooser;

/**
 *
 * @author  Alvar
 */
public class DialogoTransformadaFourier extends javax.swing.JDialog {

    Atrous principal;
    File [] files_multi;
    private static final long serialVersionUID = 1L;
    
    /** Creates new form DialogoTransformadaFourier
 * @param parent Cuadro padre en el que se dibujará el diálogo
 * @param modal true si es modal, false en caso contrario
 * @param principal Objeto principal de estado y GUI de la aplicación
 */
    public DialogoTransformadaFourier(java.awt.Frame parent, boolean modal, Atrous principal) {
        super(parent, modal);
        this.principal = principal;        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transformada de Fourier");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Examinar");
        jButton1.setActionCommand("0");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Transformada inversa");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(114, 114, 114)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

}//GEN-LAST:event_jTextField1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   int entrada = Integer.parseInt(evt.getActionCommand());
        
        principal.getFglobal().setMultiSelectionEnabled(false);
        if (entrada == 6)
        {
            principal.getFglobal().setDialogTitle(principal.getIC().buscar(103));  // Tag 103
        }
        else
        {
            principal.getFglobal().setDialogTitle(principal.getIC().buscar(104));  // Tag 104
        }
        
        principal.getFglobal().setDialogType(JFileChooser.OPEN_DIALOG);
        ExampleFileFilter filter =
                new ExampleFileFilter(
                new String [] {"tiff",
                "tif",
                "jpg",
                "jpeg",
                "jpe",
                "bil"},
                principal.getIC().buscar(88)); // Tag 88
        principal.getFglobal().resetChoosableFileFilters();
        principal.getFglobal().addChoosableFileFilter(filter);
        
        Accesorio acc = new Accesorio(principal.getFglobal(), principal.getT(), principal.getIC());
        principal.getFglobal().setAccessory(acc);
        acc.esDialogoAbrir();
        acc.setProfundidad(false);
        
        

        int retval = principal.getFglobal().showDialog(principal.getT(), null);
        if (retval == JFileChooser.APPROVE_OPTION) {
            acc = (Accesorio) principal.getFglobal().getAccessory();
            boolean separadas = acc.getSeparadas();
            File file = principal.getFglobal().getSelectedFile();
            
            switch (entrada)
            {
                case 0:jTextField1.setText(file.getPath());break;
                
                default: break;
            }
            
            this.pack();
            
        } else {
            Dialogos.dibujarMensajesError(principal.getIC(),retval);
        }
                                        
}//GEN-LAST:event_jButton1ActionPerformed

private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

}//GEN-LAST:event_jCheckBox1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    this.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    boolean inversa = false;
    inversa = jCheckBox1.isSelected();
    if (jTextField1.getText().equalsIgnoreCase(""))
        {
            return;
        }
        File file_pan = new File(jTextField1.getText());
        DialogosAux da = new DialogosAux(principal);
        List<GeoImg> pan = CargaAux.cargarArchivo(file_pan, da, principal.getT(), principal.getIC());
        this.setVisible(false);
        int nbits = 8;
        switch(pan.get(0).getImage().getSampleModel().getTransferType())
        {   
            case DataBuffer.TYPE_BYTE: nbits = 8; break;
            case DataBuffer.TYPE_USHORT: nbits = 16; break;
            default: nbits = 32;
        }
        
        Image img = pan.get(0).getImage().getAsBufferedImage().getScaledInstance(-1, -1, Image.SCALE_DEFAULT);
        
       
        ImagePlus imp = new ImagePlus(file_pan.getName(),img);
        
        FFTMod fmod = new FFTMod();
        ImagePlus fourier = fmod.doForward(imp);
        List<GeoImg> res = new ArrayList<GeoImg>();
        res.add(
                new GeoImg(null, 
                            PlanarImage.wrapRenderedImage((RenderedImage) fourier.getImage()), 
                            new File ("FFT de "+file_pan.getName()), 
                            null, 
                            null));
        principal.manejoIMGS(res, 0);
        
                
}//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
